### ISSUE TITLE
ERR Value cannot be null. (Parameter 'input') when no versioning tag present

### ISSUE THREAD

**Issue by LaoArchAngel** [skarpdev/dotnet-version-cli#116]
Our project files do not have Version, VersionPrefix, VersionSuffix, or PackageVersion tags on them.  Instead our CI pipeline was using this 
tool (v2.4.1) to just set the specific version from gitversion.

The new version currently assumes that if our desired tag is `Version`, but the `Version` property is not set, to parse the current version from `VersionPrefix` [VersionCli L134](https://github.com/skarpdev/dotnet-version-cli/blob/4a315921891d4af76722fed7b14629078ad8020e/src/VersionCli.cs#L134).  However, it doesn't try to check if the current version is null before trying to do a RegEx match [SemVer L55](https://github.com/skarpdev/dotnet-version-cli/blob/4a315921891d4af76722fed7b14629078ad8020e/src/Versioning/SemVer.cs#L55).

Would it be possible for this tool to set the appropriate version tag even if no existing tag is found?  Not sure if this is a design decision or not.

EDIT:  This is probably only relevant in the case when the `args.VersionBump` is `VersionBump.Specific`, as all other cases you might expect an existing version to be there.

**Comment by nover** [comment]
Thanks for the report @LaoArchAngel  and sorry for the late reply.

It's actually a bug and we should definitely get it fixed.

**Comment by petarhristov94** [comment]
@nover thanks for resolving the issue. I saw that you've made a new version `4.0.0`, which unfortunately is not yet available on [NuGet](https://www.nuget.org/packages/dotnet-version-cli#versions-body-tab). There the most recent version is `3.0.3`. Is that intentional?
