### ISSUE TITLE
Allow generating the version number based on output of command line

### ISSUE THREAD

**Issue by tlbdk** [skarpdev/dotnet-version-cli#12]
The main point of a tool like this is to replace the various scripting hacks to do the same with a crossplatfom tool that works in all environments, so it needs a bit of flexibility:
fx. something like this:

dotnet version --regex-format​="/^(.+)\.(\d+)$/$1.{fromCommand}-unstable/" --from-command="git rev-list HEAD --count"

1. Reads the version number in the csproj file
2. Counts the number of commits in the repo
3. Replaces the last digit in the version string with the count from before

**Comment by nover** [comment]
the purpose of this tool is actually pretty clearly stated in the documentation:
It seeks to be a npm version compatible tool for dotnet core.

This means that the intended audience is developers who wishes to do controlled releases of their libraries and applications from `master` after merging in features.

What you seek can be a combination of a static 1.0 version number and then using the `--version-suffix` when publishing the package to create "pre release" versions of your package automatically on each build on master.

**Comment by tlbdk** [comment]
You told me to create the ticket :p

This very much limits the tools use for CI/batch use, in the Java world there are about 3 version tools doing more or less the same and most people end up resorting to sed/scripting and friends. Because why would I use a plug-in if I'm already forced to use a scripting language where this is a oneliner.

**Comment by nover** [comment]
Well we don't really believe in the CI controlling the version of the software we build - after all I trust in my developers more to control the software version.

And you can get the CI to do it for you, if you publish your package with `--version-suffix` which has the only side effect of "tagging" the package as pre-release.

This flow works very well for us, and we decided to share the tool with the world, in case it could help others employing a similar flow :)
