### ISSUE TITLE
NetCore 3.1?

### ISSUE THREAD

**Issue by ClaudiuSocaci** [skarpdev/dotnet-version-cli#30]
Hi, is there a plan to upgrade this to 3.1?

**Comment by ClaudiuSocaci** [comment]
It is a great tool and we would like to use it in our build pipeline

**Comment by nover** [comment]
Hi @ClaudiuSocaci thank you for opening the issue, and yes, most definitely! I'll make sure to roll out an update today with 3.1 binaries.

**Comment by nover** [comment]
@ClaudiuSocaci I've just pushed version `1.1.1` of the dotnet version cli which is targeted for many dotnet versions, including 3.1.

**Comment by ClaudiuSocaci** [comment]
Thanks a lot @nover ! That was very fast!

**Comment by nover** [comment]
@ClaudiuSocaci Happy to help, and it's nice to know that someone out there is using our tool :)
