### ISSUE TITLE
Custom commit message not working

### ISSUE THREAD

**Issue by adrien-constant** [skarpdev/dotnet-version-cli#73]
When using the `--message` flag to customize the commit message, there is an error and the tag isn't created.

Actual
```
dotnet-version -f Host.csproj --message 'test'  patch
dotnet-version-cli version 2.1.1.0
ERR Unable to create tag
Usage: dotnet version [options]
```
Result : There is one commit with "test" message but the tag isn't created

Expected
- Tag is created

---

Another bug is when using special caracters in the message

```
dotnet-version -f Host.csproj --message '[skip ci] test'  patch
dotnet-version-cli version 2.1.1.0
ERR Unable to commit
```
Result : No commit and no tag are created.

Expected
- Commit is done with the custom message
- Tag is created

**Comment by nover** [comment]
Thanks for reporting, I'll have a look asap.

**Comment by nover** [comment]
Hi @adrien-constant - so I've been trying to replicate your issue on macOS:
> When using the --message flag to customize the commit message, there is an error and the tag isn't created.

And I'm able to pass a message both with `--message="the message"` and `--message "the message`

Can you elaborate a bit on which platform you're on and which version of dotnet sdk and `version cli` you're using? 

Regarding 
> Another bug is when using special caracters in the message

I am able to replicate, so I will try to chase this bug down.

I believe

**Comment by adrien-constant** [comment]
> Hi @adrien-constant - so I've been trying to replicate your issue on macOS:
> Can you elaborate a bit on which platform you're on and which version of dotnet sdk and `version cli` you're using?

Hi @nover , sure. Thanks for your quick answer.

```
C:\Users\adcon>dotnet --version
5.0.201

C:\Users\adcon>ver
Microsoft Windows [Version 10.0.19042.928]

dotnet-version-cli version 2.1.1.0
```

**Comment by nover** [comment]
Thanks, that will help me narrow the bug-hunting.
I've made a fix in PR #74 that solves the special chars problem on macOS, I will do some testing on nix and Windows to see if it fixes the problems there too, or whether I need some "special Windows handling" added to the stack.

**Comment by adrien-constant** [comment]
I took the PR and tried it, all tests work now

---

```
❯ dotnet-version -f Host.csproj --message 'test'  patch
dotnet-version-cli version 2.1.2.0
Bumped Host.csproj to version 1.0.1
```

---

```
❯ dotnet-version -f Host.csproj --message '[skip ci] bump version from $oldVer to $newVer'  patch
dotnet-version-cli version 2.1.2.0
Bumped Host.csproj to version 1.0.2

❯ git log
commit b99f13c72c825901904eaa18b705f2616b5f6860 (HEAD -> master, tag: v1.0.2)
Author: Adrien Constant <adrien@hashcode.fr>
Date:   Mon May 3 10:55:22 2021 +0200

    [skip ci] bump version from 1.0.1 to 1.0.2
```

Another test with custom tag is OK too :

```
❯ dotnet-version -f Host.csproj --message '[skip ci] bump version from $oldVer to $newVer' --tag 'test-$newVer'  patch
dotnet-version-cli version 2.1.2.0

❯ git tag -l
test-1.0.3
v1.0.2
```

Thanks

**Comment by nover** [comment]
@adrien-constant fantastic news - and thanks for testing it. I'll get the PR in today (hopfully) and update on nuget.

**Comment by nover** [comment]
@adrien-constant `2.1.2` is out now with a fix for your problem.
