### ISSUE TITLE
Dry-run option is not behaving as expected

### ISSUE THREAD

**Issue by feliperomero3** [skarpdev/dotnet-version-cli#98]
When using the `--dry-run` option the tool still changes the csproj, writes the commit and creates the tag.

From reading the [README](https://github.com/skarpdev/dotnet-version-cli/blob/6b3eec63171196079998a248d8352432fe71baad/README.md) file on this project, I'd expected the tool to only output the version number calculated when using the `--dry-run` option.

Example commands to reproduce the unexpected behavior:

```cmd
dotnet version --prefix preview preminor --dry-run
``` 

```cmd
dotnet version preminor --dry-run
``` 

If you need more information let me know.

PS: the .NET project I tried this tool on was [this](https://github.com/feliperomero3/ContosoConference/tree/master/src).

Thanks for the tool.

**Comment by nover** [comment]
Hi,

Thanks for the report, and for using the tool :)

that is most definitely a bug and regression. Dry run must not alter anything.

**Comment by pingvinen** [comment]
A bit late to the party, but is this not because the `--dry-run` is in the wrong place? Should the above command not be `dotnet version --dry-run --prefix preview preminor`?

**Comment by nover** [comment]
> A bit late to the party, but is this not because the `--dry-run` is in the wrong place? Should the above command not be `dotnet version --dry-run --prefix preview preminor`?
> 
> See #27

I think you're right.

**Comment by feliperomero3** [comment]
> A bit late to the party, but is this not because the `--dry-run` is in the wrong place? Should the above command not be `dotnet version --dry-run --prefix preview preminor`?
> 
> See #27

This is correct. Thank you @pingvinen 

Closing this issue as resolved.

Thanks for the tool.
